### ISSUE TITLE
Current method for staging containers does not make sense

### ISSUE THREAD

**Issue by justinrusso** [DarkPacks/SevTweaks#4]
The current method implemented (as follows) to allow staging containers does not really make sense to how staging containers/packages work. https://github.com/DarkPacks/SevTweaks/blob/95cdca75574ee6368f923367e41492de9ae39d02/src/main/java/tv/darkosto/sevtweaks/common/compat/crafttweaker/Stage.java#L180-L194

Containers/Packages can be staged in multiple stages, which I believe is a conflict if staging is done on `Stage` instead of in `Stager`

**Comment by artdude543** [comment]
Was this not resolved via this code on Stager? _(On the buildAll method)_

```java
        // Stage the Containers based on the built stage mapping.
        Map<String, List<String>> stagedContainers = stagedTypes.get(Types.CONTAINER);
        stagedContainers.forEach((container, stages) -> {
            String[] forStages = new String[]{};
            forStages = stages.toArray(forStages);

            Recipes.setContainerStage(container, forStages);
        });

        // Stage the Packages based on the built stage mapping.
        Map<String, List<String>> stagedPackages = stagedTypes.get(Types.PACKAGE);
        stagedPackages.forEach((packageName, stages) -> {
            String[] forStages = new String[]{};
            forStages = stages.toArray(forStages);

            Recipes.setPackageStage(packageName, forStages);
        });
```

**Comment by justinrusso** [comment]
Ah, I had a feeling you handled this in some way but didn't catch me.

We could look into a nicer way of adding them still, but I think its fine.

```
for stageName, stage in Stager.getStageMap() {
    stage.addContainer("primal_tech.inventory.ContainerWorkStump");
}
```

**Comment by justinrusso** [comment]
Now that I'm working on it more, I feel as though a convenience method for passing an array of stages would be ideal.

```
Stager.addPackage("test", [stageOne, stageTwo]);
```

for the time being, this is the ZS alternative:

```
function addContainerToStages(container as string, stages as Stage[]) {
	for stage in stages {
		stage.addContainer(container);
	}
}

function addPackageToStages(package as string, stages as Stage[]) {
	for stage in stages {
		stage.addPackage(package);
	}
}
```

**Comment by artdude543** [comment]
Resolved in https://github.com/DarkPacks/SevTweaks/commit/1ed679b2fce9fa0a59263d2fcd4f1554004c0038
