### ISSUE TITLE
Liquid "Item" Staging

### ISSUE THREAD

**Issue by justinrusso** [DarkPacks/SevTweaks#6]
Item Stages has a function called `stageLiquid` used to stage a `LiquidStack`. Some way to stage these would be ideal.

Liquids are also an `IIngredient`, maybe a way to determine if its a liquid can be used to then call the `stageLiquid` method?

**Comment by artdude543** [comment]
Completed in https://github.com/DarkPacks/SevTweaks/commit/1ed679b2fce9fa0a59263d2fcd4f1554004c0038
